# appveyor.yml
image: Ubuntu

build: off

clone_folder: /usr/go/src/github.com/$username/$project

environment:
  GOPATH: /usr/go/

stack: go 1.20

before_test:
  - go vet ./...

test_script:
  - go test ./...
